### ISSUE TITLE
Possible copyright issues?

### ISSUE THREAD

**Issue by XayOn** [n0w/musicLamp#1]
Your code seems to be the one from the instructable. 
It's quite simple so it shouldn't be too hard to rewrite it (or reference the original instructable)

I've already seen this code in a few places copypasted without mentioning the origin place, and really can't find the original instructables. Was it opensource? 
It'd be cool if it had a wtf license (http://es.wikipedia.org/wiki/WTFPL) but it probably doesnt =)

If you're the author of the code, notice that there are quite a lot of people using it online without copyright notice, it'd be wise to add one ( plus a license, GPL3? ;-) ).

If you really don't care, you can close this, just pointing that out in case it's somehow useful.

**Comment by n0w** [comment]
Hi,

Thanks for pointing that out; as I said in the README, I can't really remember where I found it. I just downloaded it, build the circuit and upload it here for reference purposes only, just in case somebody found it useful, like I did.

A quick search in Google yields out a few references where this snippet has been included or modified, like:

https://github.com/DavidEgolf/LightShow/blob/master/LightShow.pde
http://stackoverflow.com/questions/15646210/processing-bitwrite-arduino
